name: doctors_appointment
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1
  hive: ^2.2.3

  #  API
  dio: ^5.4.1

  #  internet check
  connectivity_plus: ^5.0.2

  #  state management
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  multiple_result: ^5.1.0
  permission_handler: ^11.3.1

  #  UI
  flutter_native_splash: ^2.3.10
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.4
  hexcolor: ^3.0.1
  flutter_screenutil: ^5.9.0
  dots_indicator: ^3.0.0
  image_picker: ^1.0.7
  pinput: ^4.0.0
  flutter_expandable_text: ^1.0.0
  page_transition: ^2.1.0
  photo_view: ^0.15.0
  custom_refresh_indicator: ^3.1.0
  jiffy: ^5.0.1
  panara_dialogs: ^0.1.5
  bottom_navy_bar: ^6.0.0
  easy_stepper: ^0.8.5+1
  flutter_offline: ^3.0.1
  flutter_easyloading: ^3.0.5
  animated_snack_bar: ^0.4.0
  video_player: ^2.7.1
  chewie: ^1.7.5
  flutter_spinkit: ^5.2.1
  animation_list: ^3.0.0
  google_fonts: ^6.0.0
  svg_flutter: ^0.0.1
  expansion_tile_card: ^3.0.0
  loading_icon_button: ^0.0.5
  skeletonizer: ^1.4.2
  rating_summary: ^1.0.3+1
  date_picker_timeline: ^1.2.5
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1

  #  other
  url_launcher: ^6.2.6
  share_plus: ^7.2.2
  equatable: ^2.0.0
  in_app_review: ^2.0.9
  in_app_update: ^4.2.3
  audioplayers: ^5.2.1
  device_preview: ^1.1.0
  easy_localization: ^3.0.7
  feedback: ^3.1.0

#  payment
  flutter_stripe: ^10.2.0
  flutter_paypal_payment: ^1.0.6

  #firebase
  firebase_core: ^2.16.0
  google_sign_in: ^6.2.1
  firebase_messaging: ^14.7.19
  firebase_crashlytics: ^3.4.18

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
   - assets/images/
   - assets/icons/
   - assets/translations/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
