// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT_vNZgAHtsM44ZSgAe0Wi04XHIQ0JRB4',
    appId: '1:278941682571:web:2bbdd473537f8972cefd8e',
    messagingSenderId: '278941682571',
    projectId: 'medimeet-6cd6c',
    authDomain: 'medimeet-6cd6c.firebaseapp.com',
    storageBucket: 'medimeet-6cd6c.appspot.com',
    measurementId: 'G-LG9ZY44CV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrAp6y4Zmvxg9JEhe03dPGCmqLhtBzngk',
    appId: '1:278941682571:android:3aebcaa6aabd196ecefd8e',
    messagingSenderId: '278941682571',
    projectId: 'medimeet-6cd6c',
    storageBucket: 'medimeet-6cd6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn6K7b18QepWQBOQZ2DlmuNQx-QoVJESE',
    appId: '1:278941682571:ios:06d4f9e1ad145cd7cefd8e',
    messagingSenderId: '278941682571',
    projectId: 'medimeet-6cd6c',
    storageBucket: 'medimeet-6cd6c.appspot.com',
    iosBundleId: 'com.example.doctorsAppointment',
  );
}
